class CopyGoProMessages {
    static $NameNotSpecified = "エラー！ デバイス名が指定されていません"
    static $LocalDestinationNotSpecified = "エラー！ コピー先ローカルフォルダが指定されていません（ローカルフォルダはネットワークフォルダを指定することも可能です）"
    static $OneDriveDestinationNotSpecified = "コピー先の OneDrive フォルダが指定されていないため OneDrive へのコピーは行われません"
    static $GetFiles = "フォルダ内のファイル一覧を取得しています： デバイス:{0}、フォルダ: {1}"
    static $MTPFileFound = "デバイス上のファイルを発見しました: ファイル数: {0}"
    static $MTPFileFoundTotal = "デバイス上のファイルを発見しました: 合計ファイル数: {0}"
    static $OneDriveSignIn = "OneDrive にサインインします"
    static $DeviceAccessOK = "デバイスへのアクセスに成功しました"
    static $DateLimitSet = "指定日以降のファイルを処理します: {0} "
    static $FileExistsSkip = "コピー先にファイルを発見、スキップします: {0}"
    static $FileExistsRename = "コピー先にファイルを発見、日付を付けた名前に変更します: {0}"
    static $Copying = "ファイルをコピーします: {0}"
    static $CopyingTo = "コピー処理を開始します。コピー先： {0}"
    static $CopyOD = "OneDrive コピー処理を開始: オリジナル:{0} コピー元: {1}"
    static $SubFolderCreate = "サブフォルダを作成します: フォルダ名: {0} 親フォルダ: {1}"
    static $Uploading = "ファイルをアップロードします: コピー元: {0} ファイルサイズ: {1} アップロード先: {2}"
    static $Renaming = "ファイル名を変更します: {0} -> {1}"
    static $WaitFile = "ファイルがありません。待機します: {0} 待機時間: {1}秒"
    static $AllDone = "コピー処理がすべて完了しました！"
    static $NoDeviceToCopy = "デバイスが見つかりませんでした"
    static $NoFileToCopy = "コピー対象ファイルが見つかりませんでした"
    static $NoDCIM = "DCIM フォルダが見つかりませんでした: {0}"
    static $NoDestinationFolder = "コピー先のフォルダがありません: {0}"
    static $NoDiskFree = "ディスク容量が不足しています。残量量: {0}"
    static $CannotUploadODFromMTP = "エラー！ GoPro デバイスから OneDrive へ直接アップロードすることはできません。 -Cache または -LocalDestination を使用する必要があります"

}